In [1]:
'''
    1）计算各区(district)的薪资(salary)均值;
    2) 重新按照上一题要求进行分组，但不使用 district 做为索引
    3）计算并提取平均薪资最高的区；
    4）计算不同行政区(district)，不同规模公司(companySize)出现的次数
    5）计算上一题，每个区出现的公司数量
    6）将数据按照 district、salary 进行分组，并查看各分组内容
    7）将数据按照 district、salary 进行分组，并查看西湖区薪资为 30000 的工作
'''
import pandas 
import numpy
df = pandas.read_csv(
    'C:\\Users\\26440\\Desktop\\jupyter_ipynb\\python_source\\data\\某招聘网站数据.csv'
    ,encoding='utf-8'
    )
df

,positionName,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,createTime,district,salary,workYear,jobNature,education,positionAdvantage,imState,score,matchScore,famousCompany
0,数据分析,50-150人,"移动互联网,电商",A轮,"['绩效奖金', '带薪年假', '定期体检', '弹性工作']",产品|需求|项目类,数据分析,数据分析,2020/3/16 11:00,余杭区,37500,1-3年,全职,本科,五险一金、弹性工作、带薪年假、年度体检,today,233,15.101875,False
1,数据建模,150-500人,电商,B轮,"['年终奖金', '做五休二', '六险一金', '子女福利']",开发|测试|运维类,数据开发,建模,2020/3/16 11:08,滨江区,15000,3-5年,全职,本科,"六险一金,定期体检,丰厚年终",disabled,176,32.559414,False
2,数据分析,2000人以上,"移动互联网,企业服务",上市公司,"['节日礼物', '年底双薪', '股票期权', '带薪年假']",产品|需求|项目类,数据分析,数据分析,2020/3/16 10:33,江干区,3500,1-3年,全职,本科,五险一金 周末双休 不加班 节日福利,today,80,14.972357,False
3,数据分析,500-2000人,电商,D轮及以上,"['生日趴', '每月腐败基金', '每月补贴', '年度旅游']",开发|测试|运维类,数据开发,数据分析,2020/3/16 10:10,江干区,45000,3-5年,全职,本科,年终奖等,threeDays,68,12.874153,True
4,数据分析,2000人以上,物流丨运输,上市公司,"['技能培训', '免费班车', '专项奖金', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,2020/3/16 9:56,余杭区,30000,3-5年,全职,大专,五险一金,disabled,66,12.755375,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,数据分析师,500-2000人,"移动互联网,医疗丨健康",C轮,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",产品|需求|项目类,数据分析,数据分析,2020/3/11 16:45,萧山区,25000,3-5年,全职,不限,大牛老板，开放环境，民生行业，龙头公司,threeDays,0,0.314259,False
101,商业数据分析,500-2000人,"移动互联网,电商",C轮,"['节日礼物', '股票期权', '带薪年假', '年度旅游']",市场|商务类,市场|营销,商业数据分析,2020/3/14 17:38,余杭区,35000,1-3年,全职,硕士,五险一金、带薪休假,threeDays,0,0.283276,False
102,奔驰·耀出行-BI数据分析专家,150-500人,移动互联网,不需要融资,[],开发|测试|运维类,数据开发,数据分析,2020/3/14 22:39,滨江区,30000,3-5年,全职,本科,奔驰 吉利 世界500强,threeDays,0,0.256719,False
103,BI数据分析师,2000人以上,电商,上市公司,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",开发|测试|运维类,数据开发,数据分析,2020/3/9 15:00,余杭区,20000,3-5年,全职,本科,阿里巴巴；商业智能；,threeDays,0,0.281062,True
104,数据分析专家-LQ(J181203029),2000人以上,汽车丨出行,不需要融资,"['弹性工作', '节日礼物', '岗位晋升', '技能培训']",产品|需求|项目类,数据分析,其他数据分析,2020/3/13 18:24,西湖区,21500,5-10年,全职,本科,广阔平台诱人福利,disabled,0,0.159343,True

In [2]:
print('各区的薪资均值为：\n',df.groupby(by='district')['salary'].mean().
      apply(lambda x:round(x,2)))
print(df.groupby(by='district',as_index=False)['salary'])
#ascending 是 升序  ascending=False 则是降序
df.groupby(by='district',as_index=False)['salary'].mean().sort_values('salary',ascending=False).head(1)

#方法2：找出最大值
#df.groupby(by='district',as_index=False)['salary'].mean().sort_values('salary').max()

各区的薪资均值为：
 district
上城区    26250.00
下沙     30000.00
余杭区    33583.33
拱墅区    28500.00
江干区    25250.00
滨江区    31428.57
萧山区    36250.00
西湖区    30893.94
Name: salary, dtype: float64
<pandas.core.groupby.generic.SeriesGroupBy object at 0x0000022814408260>

  district   salary
6      萧山区  36250.0

In [3]:
#计算上一题，每个区出现的公司数量
print('不同规模公司出现的数量：\n',df.groupby(by='district')['companySize'].count())

#计算不同行政区(district)，不同规模公司(companySize)出现的次数
df.groupby(by=['district','companySize'])['companySize'].size()

不同规模公司出现的数量：
 district
上城区     2
下沙      1
余杭区    36
拱墅区     4
江干区     4
滨江区    21
萧山区     4
西湖区    33
Name: companySize, dtype: int64

district  companySize
上城区       50-150人         2
下沙        150-500人        1
余杭区       150-500人       13
          2000人以上        14
          50-150人         7
          500-2000人       2
拱墅区       2000人以上         1
          50-150人         1
          500-2000人       2
江干区       2000人以上         2
          500-2000人       2
滨江区       150-500人       14
          2000人以上         6
          500-2000人       1
萧山区       50-150人         1
          500-2000人       3
西湖区       15-50人          1
          150-500人        7
          2000人以上        11
          50-150人         5
          500-2000人       9
Name: companySize, dtype: int64

In [4]:
#数据按照 district、salary 进行分组，并查看各分组内容
data = df.groupby(by=['district','salary'])
data.groups

{('上城区', 22500): [81], ('上城区', 30000): [97], ('下沙', 30000): [31], ('余杭区', 7500): [84], ('余杭区', 20000): [52, 103], ('余杭区', 22500): [23, 51], ('余杭区', 25000): [62], ('余杭区', 27500): [24, 49], ('余杭区', 29000): [93], ('余杭区', 30000): [4, 10, 13, 18, 59, 61, 65, 68, 74, 76, 86, 92, 94], ('余杭区', 35000): [101], ('余杭区', 37500): [0, 32, 38, 39, 41], ('余杭区', 40000): [60, 87], ('余杭区', 45000): [25], ('余杭区', 50000): [5, 64, 90], ('余杭区', 60000): [8, 82], ('拱墅区', 24000): [72], ('拱墅区', 30000): [54, 89, 96], ('江干区', 3500): [2], ('江干区', 22500): [45], ('江干区', 30000): [73], ('江干区', 45000): [3], ('滨江区', 7500): [83], ('滨江区', 15000): [1], ('滨江区', 20000): [21, 40], ('滨江区', 22500): [37], ('滨江区', 30000): [22, 53, 55, 58, 67, 80, 102], ('滨江区', 32500): [26], ('滨江区', 37500): [17, 28, 57, 77], ('滨江区', 42500): [91], ('滨江区', 45000): [43, 47], ('滨江区', 50000): [44], ('萧山区', 25000): [100], ('萧山区', 30000): [6], ('萧山区', 45000): [66, 69], ('西湖区', 6500): [71], ('西湖区', 20000): [12], ('西湖区', 21500): [104], ('西湖区', 22500): [48, 70], ('西湖区', 24000): [42], ('西湖区', 25000): [56], ('西湖区', 26500): [78], ('西湖区', 27000): [75], ('西湖区', 27500): [15, 20, 50, 63], ('西湖区', 30000): [11, 27, 33, 34, 85, 88, 98], ('西湖区', 35000): [7], ('西湖区', 36500): [99], ('西湖区', 37500): [14, 16, 19, 30, 36, 79, 95], ('西湖区', 40000): [9, 35], ('西湖区', 45000): [29, 46]}

In [5]:
group = data.get_group(('西湖区',30000))
group

,positionName,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,createTime,district,salary,workYear,jobNature,education,positionAdvantage,imState,score,matchScore,famousCompany
11,大数据分析工程师(J11108),2000人以上,"移动互联网,企业服务",上市公司,"['技能培训', '年底双薪', '带薪年假', '岗位晋升']",开发|测试|运维类,数据开发,数据分析,2020/3/16 9:25,西湖区,30000,应届毕业生,全职,本科,六险一金 带薪年假 年度体检 周末双休,today,17,4.245066,False
27,数据分析经理,2000人以上,硬件,不需要融资,"['年终分红', '带薪年假', '年度旅游', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,2020/3/16 11:24,西湖区,30000,5-10年,全职,本科,"股票期权,千万级用户,试用期全薪",today,6,1.164082,True
33,数据分析师（社招）,500-2000人,移动互联网,上市公司,"['绩效奖金', '股票期权', '年底双薪', '专项奖金']",产品|需求|项目类,数据分析,数据分析,2020/3/16 11:18,西湖区,30000,应届毕业生,全职,不限,16-18薪 大数据A股上市公司,today,15,1.020377,True
34,商业数据分析师,50-150人,"移动互联网,企业服务",B轮,"['定期体检', '帅哥多', '领导好', '美女多']",市场|商务类,市场|营销,商业数据分析,2020/3/16 11:13,西湖区,30000,1-3年,全职,硕士,"发挥空间大,职业发展好",today,5,1.095633,False
85,高级数据分析师,500-2000人,移动互联网,上市公司,"['包午餐晚餐', '奖金多多多', '零食下午茶', '全员出国游']",产品|需求|项目类,数据分析,数据分析,2020/3/14 21:28,西湖区,30000,3-5年,全职,本科,福利好，年轻有活力，行业前景好,today,2,0.389503,False
88,资深数据分析师,500-2000人,移动互联网,A轮,"['岗位晋升', '年度旅游', '年底双薪', '午餐补助']",产品|需求|项目类,数据分析,数据分析,2020/3/15 19:43,西湖区,30000,3-5年,全职,大专,"六险一金,餐饮补贴,双休,出国旅游",today,1,0.502371,False
98,数据分析建模工程师,50-150人,"数据服务,信息安全",A轮,"['午餐补助', '带薪年假', '16到18薪', '法定节假日']",开发|测试|运维类,人工智能,机器学习,2020/3/14 19:00,西湖区,30000,1-3年,全职,本科,海量数据 全链路建模实践 16-18薪,threeDays,0,0.356308,False

In [6]:
'''
    2.分组计算不同行政区(district)，薪水(salary)的最小值、最大值和平均值
'''
df.groupby(by='district')['salary'].agg([numpy.min,numpy.max,numpy.mean])

C:\Users\26440\AppData\Local\Temp\ipykernel_11808\1939973341.py:4: FutureWarning: The provided callable <function min at 0x000002281306AFC0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(by='district')['salary'].agg([numpy.min,numpy.max,numpy.mean])
C:\Users\26440\AppData\Local\Temp\ipykernel_11808\1939973341.py:4: FutureWarning: The provided callable <function max at 0x000002281306AE80> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(by='district')['salary'].agg([numpy.min,numpy.max,numpy.mean])
C:\Users\26440\AppData\Local\Temp\ipykernel_11808\1939973341.py:4: FutureWarning: The provided callable <function mean at 0x000002281306B880> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(by='district')['salary'].agg([numpy.min,numpy.max,numpy.mean])

            min    max          mean
district
上城区       22500  30000  26250.000000
下沙        30000  30000  30000.000000
余杭区        7500  60000  33583.333333
拱墅区       24000  30000  28500.000000
江干区        3500  45000  25250.000000
滨江区        7500  50000  31428.571429
萧山区       25000  45000  36250.000000
西湖区        6500  45000  30893.939394

In [7]:
#对不同岗位(positionName)进行分组，并统计其薪水(salary)中位数和得分(score)均值
df.groupby(by='positionName').agg({'salary':numpy.median,'score':numpy.mean})

C:\Users\26440\AppData\Local\Temp\ipykernel_11808\2423357511.py:2: FutureWarning: The provided callable <function median at 0x00000228132AA5C0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby(by='positionName').agg({'salary':numpy.median,'score':numpy.mean})
C:\Users\26440\AppData\Local\Temp\ipykernel_11808\2423357511.py:2: FutureWarning: The provided callable <function mean at 0x000002281306B880> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(by='positionName').agg({'salary':numpy.median,'score':numpy.mean})

                          salary       score
positionName
BI数据分析师                  20000.0    2.666667
bi数据分析师                  40000.0    5.000000
业务与数据分析师                 30000.0    3.000000
产品经理/数据分析（核心业务）-2020届春招  60000.0    3.000000
产品运营（偏数据分析）              27500.0   15.000000
商业数据分析                   35000.0    0.000000
商业数据分析师                  37500.0    5.000000
商业数据分析师（阿里数据银行）          22500.0    3.000000
大数据分析工程师(J11108)         30000.0   17.000000
大数据建模总监                  37500.0   14.000000
奔驰·耀出行-BI数据分析专家          30000.0    0.000000
奔驰耀出行-战略数据分析师            42500.0    1.000000
店铺数据分析师                  30000.0    6.000000
数据分析                     30000.0   82.714286
数据分析-2020届春招             30000.0    4.000000
数据分析专员                   26250.0    3.000000
数据分析专家                   31250.0    8.166667
数据分析专家-LQ(J181203029)    21500.0    0.000000
数据分析专家03-10-217          23750.0    4.500000
数据分析专家（游戏业务）             37500.0   12.000000
数据分析实习生                  40000.0    4.000000
数据分析实习生 (MJ000087)       26500.0    3.000000
数据分析工程师                  20000.0   16.000000
数据分析师                    37500.0    6.500000
数据分析师 (MJ000250)         27500.0    4.500000
数据分析师(J10147)            37500.0    3.000000
数据分析师-Lark               30000.0    2.000000
数据分析师-企业SaaS应用           40000.0    2.000000
数据分析师/BI                 45000.0    5.000000
数据分析师（保险）13-01-19        40000.0    4.000000
数据分析师（社招）                30000.0   15.000000
数据分析师（财务方向）              37500.0    5.000000
数据分析建模工程师                30000.0    0.000000
数据分析建模工程师（校招）            36500.0    0.000000
数据分析经理                   30000.0    6.500000
数据分析负责人 or 数据分析师         30000.0    4.000000
数据建模                     15000.0  176.000000
数据建模专家-杭州-01546          30000.0   12.000000
数据建模工程师                  36250.0   24.000000
旅游大数据分析师（杭州）             30000.0    1.000000
智能数据分析引擎研发专家             30000.0    3.000000
浙江数据分析师                  37500.0    5.000000
解决方案顾问/数据分析师             25000.0    4.500000
财务数据分析师                  37500.0    4.500000
资深数据分析/数据分析专家G00796      45000.0    4.000000
资深数据分析专员                 30000.0    1.000000
资深数据分析师                  30000.0    6.666667
资深数据分析师 (MJ000088)       25000.0    4.000000
资深数据分析师（商品方向）G01053      45000.0    4.000000
资深数据分析师（杭州）              37500.0   15.000000
金融数据分析师                  22500.0    5.000000
银行数据分析岗                  50000.0    5.000000
高级数据分析专员                 22500.0    4.000000
高级数据分析师                  30000.0    3.666667
高级财务数据分析师                28750.0    4.500000

In [8]:
# 对不同行政区(district)进行分组，并统计薪水(salary)的均值、中位数、方差，以及得分(score)的均值
df.groupby(by='district').agg({'salary':[numpy.mean,numpy.median,numpy.var],'score':numpy.mean})

C:\Users\26440\AppData\Local\Temp\ipykernel_11808\2353359562.py:2: FutureWarning: The provided callable <function mean at 0x000002281306B880> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(by='district').agg({'salary':[numpy.mean,numpy.median,numpy.var],'score':numpy.mean})
C:\Users\26440\AppData\Local\Temp\ipykernel_11808\2353359562.py:2: FutureWarning: The provided callable <function median at 0x00000228132AA5C0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby(by='district').agg({'salary':[numpy.mean,numpy.median,numpy.var],'score':numpy.mean})
C:\Users\26440\AppData\Local\Temp\ipykernel_11808\2353359562.py:2: FutureWarning: The provided callable <function var at 0x000002281306BB00> is currently using SeriesGroupBy.var. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "var" instead.
  df.groupby(by='district').agg({'salary':[numpy.mean,numpy.median,numpy.var],'score':numpy.mean})
C:\Users\26440\AppData\Local\Temp\ipykernel_11808\2353359562.py:2: FutureWarning: The provided callable <function mean at 0x000002281306B880> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(by='district').agg({'salary':[numpy.mean,numpy.median,numpy.var],'score':numpy.mean})

                salary                             score
                  mean   median           var       mean
district
上城区       26250.000000  26250.0  2.812500e+07   2.000000
下沙        30000.000000  30000.0           NaN   6.000000
余杭区       33583.333333  30000.0  1.178929e+08  15.166667
拱墅区       28500.000000  30000.0  9.000000e+06   2.750000
江干区       25250.000000  26250.0  2.977500e+08  39.250000
滨江区       31428.571429  30000.0  1.091071e+08  12.952381
萧山区       36250.000000  37500.0  1.062500e+08  18.250000
西湖区       30893.939394  30000.0  6.340246e+07   8.060606

In [9]:
#计算各行政区的企业领域（industryField）包含电商的总数（通过匿名函数）
df['Sum'] = df['industryField'].apply(lambda x: '电商' in x)
ecommerce_counts = df.groupby('district')['Sum'].agg(['sum'])
print(ecommerce_counts)
#df.groupby(by='district').agg({'industryField':lambda x:x.sum()},axis=0)

          sum
district
上城区         0
下沙          1
余杭区         9
拱墅区         0
江干区         2
滨江区         9
萧山区         3
西湖区         4

In [10]:
df['salary1'] = df['salary'].agg(lambda x:x+500,axis=0)
df

C:\Users\26440\AppData\Local\Temp\ipykernel_11808\3502783453.py:1: FutureWarning: using <function <lambda> at 0x0000022815574CC0> in Series.agg cannot aggregate and has been deprecated. Use Series.transform to keep behavior unchanged.
  df['salary1'] = df['salary'].agg(lambda x:x+500,axis=0)

,positionName,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,createTime,district,...,workYear,jobNature,education,positionAdvantage,imState,score,matchScore,famousCompany,Sum,salary1
0,数据分析,50-150人,"移动互联网,电商",A轮,"['绩效奖金', '带薪年假', '定期体检', '弹性工作']",产品|需求|项目类,数据分析,数据分析,2020/3/16 11:00,余杭区,...,1-3年,全职,本科,五险一金、弹性工作、带薪年假、年度体检,today,233,15.101875,False,True,38000
1,数据建模,150-500人,电商,B轮,"['年终奖金', '做五休二', '六险一金', '子女福利']",开发|测试|运维类,数据开发,建模,2020/3/16 11:08,滨江区,...,3-5年,全职,本科,"六险一金,定期体检,丰厚年终",disabled,176,32.559414,False,True,15500
2,数据分析,2000人以上,"移动互联网,企业服务",上市公司,"['节日礼物', '年底双薪', '股票期权', '带薪年假']",产品|需求|项目类,数据分析,数据分析,2020/3/16 10:33,江干区,...,1-3年,全职,本科,五险一金 周末双休 不加班 节日福利,today,80,14.972357,False,False,4000
3,数据分析,500-2000人,电商,D轮及以上,"['生日趴', '每月腐败基金', '每月补贴', '年度旅游']",开发|测试|运维类,数据开发,数据分析,2020/3/16 10:10,江干区,...,3-5年,全职,本科,年终奖等,threeDays,68,12.874153,True,True,45500
4,数据分析,2000人以上,物流丨运输,上市公司,"['技能培训', '免费班车', '专项奖金', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,2020/3/16 9:56,余杭区,...,3-5年,全职,大专,五险一金,disabled,66,12.755375,True,False,30500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,数据分析师,500-2000人,"移动互联网,医疗丨健康",C轮,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",产品|需求|项目类,数据分析,数据分析,2020/3/11 16:45,萧山区,...,3-5年,全职,不限,大牛老板，开放环境，民生行业，龙头公司,threeDays,0,0.314259,False,False,25500
101,商业数据分析,500-2000人,"移动互联网,电商",C轮,"['节日礼物', '股票期权', '带薪年假', '年度旅游']",市场|商务类,市场|营销,商业数据分析,2020/3/14 17:38,余杭区,...,1-3年,全职,硕士,五险一金、带薪休假,threeDays,0,0.283276,False,True,35500
102,奔驰·耀出行-BI数据分析专家,150-500人,移动互联网,不需要融资,[],开发|测试|运维类,数据开发,数据分析,2020/3/14 22:39,滨江区,...,3-5年,全职,本科,奔驰 吉利 世界500强,threeDays,0,0.256719,False,False,30500
103,BI数据分析师,2000人以上,电商,上市公司,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",开发|测试|运维类,数据开发,数据分析,2020/3/9 15:00,余杭区,...,3-5年,全职,本科,阿里巴巴；商业智能；,threeDays,0,0.281062,True,True,20500
104,数据分析专家-LQ(J181203029),2000人以上,汽车丨出行,不需要融资,"['弹性工作', '节日礼物', '岗位晋升', '技能培训']",产品|需求|项目类,数据分析,其他数据分析,2020/3/13 18:24,西湖区,...,5-10年,全职,本科,广阔平台诱人福利,disabled,0,0.159343,True,False,22000

In [12]:
#计算各行政区的企业领域（industryField）包含电商的总数（通过匿名函数） --str.contains 返回识别字符串
df.groupby('district')['industryField'].apply(lambda x:x.str.contains('电商').sum())

district
上城区    0
下沙     1
余杭区    9
拱墅区    0
江干区    2
滨江区    9
萧山区    3
西湖区    4
Name: industryField, dtype: int64

In [16]:
#transform 能够把整个DataFrame 的所有元素进行操作 --> 且能够返回原始 DataFrame 相同形状的结果
#在第1题数据的基础上，在原数据对象df 中新增一列，数值为该区的平均薪资水平   round() 表示保留x位小数
df['平均薪资水平'] = df.groupby('district')['salary'].transform(numpy.mean).round(2)
df

C:\Users\26440\AppData\Local\Temp\ipykernel_11808\1525041248.py:2: FutureWarning: The provided callable <function mean at 0x000002281306B880> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df['平均薪资水平'] = df.groupby('district')['salary'].transform(numpy.mean).round(2)

,positionName,companySize,industryField,financeStage,companyLabelList,firstType,secondType,thirdType,createTime,district,...,jobNature,education,positionAdvantage,imState,score,matchScore,famousCompany,Sum,salary1,平均薪资水平
0,数据分析,50-150人,"移动互联网,电商",A轮,"['绩效奖金', '带薪年假', '定期体检', '弹性工作']",产品|需求|项目类,数据分析,数据分析,2020/3/16 11:00,余杭区,...,全职,本科,五险一金、弹性工作、带薪年假、年度体检,today,233,15.101875,False,True,38000,33583.33
1,数据建模,150-500人,电商,B轮,"['年终奖金', '做五休二', '六险一金', '子女福利']",开发|测试|运维类,数据开发,建模,2020/3/16 11:08,滨江区,...,全职,本科,"六险一金,定期体检,丰厚年终",disabled,176,32.559414,False,True,15500,31428.57
2,数据分析,2000人以上,"移动互联网,企业服务",上市公司,"['节日礼物', '年底双薪', '股票期权', '带薪年假']",产品|需求|项目类,数据分析,数据分析,2020/3/16 10:33,江干区,...,全职,本科,五险一金 周末双休 不加班 节日福利,today,80,14.972357,False,False,4000,25250.00
3,数据分析,500-2000人,电商,D轮及以上,"['生日趴', '每月腐败基金', '每月补贴', '年度旅游']",开发|测试|运维类,数据开发,数据分析,2020/3/16 10:10,江干区,...,全职,本科,年终奖等,threeDays,68,12.874153,True,True,45500,25250.00
4,数据分析,2000人以上,物流丨运输,上市公司,"['技能培训', '免费班车', '专项奖金', '岗位晋升']",产品|需求|项目类,数据分析,数据分析,2020/3/16 9:56,余杭区,...,全职,大专,五险一金,disabled,66,12.755375,True,False,30500,33583.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,数据分析师,500-2000人,"移动互联网,医疗丨健康",C轮,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",产品|需求|项目类,数据分析,数据分析,2020/3/11 16:45,萧山区,...,全职,不限,大牛老板，开放环境，民生行业，龙头公司,threeDays,0,0.314259,False,False,25500,36250.00
101,商业数据分析,500-2000人,"移动互联网,电商",C轮,"['节日礼物', '股票期权', '带薪年假', '年度旅游']",市场|商务类,市场|营销,商业数据分析,2020/3/14 17:38,余杭区,...,全职,硕士,五险一金、带薪休假,threeDays,0,0.283276,False,True,35500,33583.33
102,奔驰·耀出行-BI数据分析专家,150-500人,移动互联网,不需要融资,[],开发|测试|运维类,数据开发,数据分析,2020/3/14 22:39,滨江区,...,全职,本科,奔驰 吉利 世界500强,threeDays,0,0.256719,False,False,30500,31428.57
103,BI数据分析师,2000人以上,电商,上市公司,"['技能培训', '年底双薪', '节日礼物', '绩效奖金']",开发|测试|运维类,数据开发,数据分析,2020/3/9 15:00,余杭区,...,全职,本科,阿里巴巴；商业智能；,threeDays,0,0.281062,True,True,20500,33583.33
104,数据分析专家-LQ(J181203029),2000人以上,汽车丨出行,不需要融资,"['弹性工作', '节日礼物', '岗位晋升', '技能培训']",产品|需求|项目类,数据分析,其他数据分析,2020/3/13 18:24,西湖区,...,全职,本科,广阔平台诱人福利,disabled,0,0.159343,True,False,22000,30893.94